Change password
IrinaMilekhina/WebTeam_Project pull request #100
Opened 2022-07-01 05:39 UTC by Bekham

2022-07-02 12:48 UTC, IrinaMilekhina requested changes
требуется rebase

2022-07-07 14:30 UTC, morozov-git approved these changes
Работает только как изменение пароля у авторизованного пользователя. 
Приходит одно письмо со ссылкой (раньше у меня приходило по два письма  за раз).
Есть конфликты в файле users/views.py (если их исправить то все работает)

2022-07-07 19:22 UTC, morozov-git commented on ProductPlatform/users/views.py
> +        user = Profile.objects.get(pk=self.request.user.pk)
Антон, посмотри, пожалуйста.

Если эту функцию переписать, например вот так:
`
def form_valid(self, form):

        try:
            user = Profile.objects.get(email=form.cleaned_data['email'])
            if user:
                return super().form_valid(form)
        except:
            form.errors['InvalidEmail'] = 'Введен некорректный email. Введите email, указанный при регистрации.'
            return super().form_invalid(form)
`



То будет работать для всех пользователей, которые есть в базе, но не смогли зайти в личный кабинет.

2022-07-07 19:26 UTC, morozov-git approved these changes, later dismissed

2022-07-09 09:18 UTC, IrinaMilekhina submitted a review, later dismissed

2022-07-09 12:57 UTC, morozov-git approved these changes, later dismissed

2022-07-09 13:14 UTC, byDemid commented
при вводе легкого пароля (к примеру 1234qwer), форма просто очищается, и не уведомляет что не так

2022-07-11 08:39 UTC, byDemid approved these changes

2022-07-11 19:05 UTC, DanielPivnev approved these changes

2022-07-12 15:41 UTC, merged