Личный кабинет (фронт)
IrinaMilekhina/WebTeam_Project pull request #11
Opened 2022-06-06 18:00 UTC by Bekham

2022-06-07 13:16 UTC, EuGeN-PYTHON requested changes
ProductPlatform/users/templates/profile/profile_orders.html
36 строка лишний символ "кавычки":

<div class="hamburger"">

2022-06-07 18:16 UTC, DanielPivnev commented on ProductPlatform/users/templates/profile/profile_main.html
> +    <meta name="description" content="">
это можно убрать

2022-06-07 21:20 UTC, Sten451 commented
В целом мне нравится, сам код не смотрел, только визуальное оформление, может стоит подумать чтобы где то выводить статус Заказчик ли это или Поставщик, возможно отвести под аватарку место.
Пока не знаю как реализовывается количество просмотров.....

2022-06-08 13:39 UTC, DanielPivnev commented on ProductPlatform/users/templates/profile/profile_orders_history.html
> +    <meta name="description" content="">
это можно убрать

2022-06-08 13:48 UTC, DanielPivnev commented on ProductPlatform/users/templates/profile/profile_orders_history.html
> +    <link rel="stylesheet" href="../../../static/profile/assets/theme/css/style.css">
лучше сразу с шабланизатором писать

2022-06-09 17:11 UTC, Bekham commented on ProductPlatform/users/templates/profile/profile_main.html
> +    <meta name="description" content="">
исправил

2022-06-09 17:11 UTC, Bekham commented on ProductPlatform/users/templates/profile/profile_orders_history.html
> +    <meta name="description" content="">
исправил, адаптировал под использоание base.html

2022-06-09 17:11 UTC, Bekham commented on ProductPlatform/users/templates/profile/profile_orders_history.html
> +    <link rel="stylesheet" href="../../../static/profile/assets/theme/css/style.css">
исправил

2022-06-14 16:32 UTC, DanielPivnev commented on ProductPlatform/users/templates/users/profile_orders.html
> +                    <div class="top-line row">
Лучше думаю сразу в for положить

2022-06-14 18:59 UTC, IrinaMilekhina commented
Будет перелит во второй релиз двумя ветками

2022-06-14 18:59 UTC, closed without merging