Feature/112 base template
IrinaMilekhina/WebTeam_Project pull request #12
Opened 2022-06-07 17:38 UTC by DanielPivnev

2022-06-07 19:15 UTC, IrinaMilekhina requested changes

2022-06-07 19:15 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/base_site.html
> +<nav class="navbar navbar-expand-lg fixed-top bg-green">
базовый шаблон не должен включать меню. Скинула примеры в чат

2022-06-07 19:15 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/base_site.html
> +{% load static %}
статика загружается после <!doctype html>

2022-06-07 19:15 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/base_site.html
> +<html lang="en">
Почему?

2022-06-07 19:15 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/base_site.html
> +<footer class="footer  mt-auto py-3 bg-green">
а зачем нам вообще футер? Что в нем будет?

2022-06-07 19:15 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/base_site.html
> +<footer class="footer  mt-auto py-3 bg-green">
и если он будет, то почему не в блоке?

2022-06-07 19:15 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/base_site.html
> +<link href="{% static "bootstrap-5.2.0-beta1-dist/css/bootstrap.css" %}" rel="stylesheet">
внезапное место для подключения =) посмотри пример, который я скинула

2022-06-07 20:23 UTC, byDemid commented on ProductPlatform/users/templates/users/base_site.html
> +    <link href="{% static "css/main.css" %}" rel="stylesheet">
возможно нужны разные кавычки. внутри двойных одинарные .

2022-06-07 20:24 UTC, byDemid commented on ProductPlatform/users/templates/users/base_site.html
> +<script src="{% static "bootstrap-5.2.0-beta1-dist/js/bootstrap.bundle.js" %}"></script>
так же про кавычки , внешние и внутренние

2022-06-08 12:46 UTC, DanielPivnev commented on ProductPlatform/users/templates/users/base_site.html
> +<nav class="navbar navbar-expand-lg fixed-top bg-green">
исправил

2022-06-08 12:48 UTC, DanielPivnev commented on ProductPlatform/users/templates/users/base_site.html
> +<html lang="en">
не понял, но если про lang, то его html требует (поменял en на ru)

2022-06-08 12:50 UTC, DanielPivnev commented on ProductPlatform/users/templates/users/base_site.html
> +<footer class="footer  mt-auto py-3 bg-green">
исправил (вернее убрал), но для главной оставлю, потому-что там с ним красивей

2022-06-08 12:50 UTC, DanielPivnev commented on ProductPlatform/users/templates/users/base_site.html
> +<link href="{% static "bootstrap-5.2.0-beta1-dist/css/bootstrap.css" %}" rel="stylesheet">
исправил

2022-06-08 12:50 UTC, DanielPivnev commented on ProductPlatform/users/templates/users/base_site.html
> +    <link href="{% static "css/main.css" %}" rel="stylesheet">
исправил

2022-06-08 12:50 UTC, DanielPivnev commented on ProductPlatform/users/templates/users/base_site.html
> +<script src="{% static "bootstrap-5.2.0-beta1-dist/js/bootstrap.bundle.js" %}"></script>
исправил

2022-06-08 17:46 UTC, byDemid approved these changes, later dismissed

2022-06-08 17:46 UTC, byDemid commented on ProductPlatform/users/templates/users/base.html
> +{% load static %}
Все же думаю его можно и на самый верх, смотрел многие стримы, везде писали на самом верху

2022-06-08 18:15 UTC, IrinaMilekhina approved these changes, later dismissed

2022-06-08 18:29 UTC, IrinaMilekhina approved these changes

2022-06-08 19:19 UTC, byDemid approved these changes

2022-06-08 19:37 UTC, merged