314 add image background
IrinaMilekhina/WebTeam_Project pull request #136
Opened 2022-07-06 21:16 UTC by Sten451

Картинки конечно не идеальные, со вкусом у меня всегда сложности

2022-07-07 13:23 UTC, morozov-git submitted a review, later dismissed

2022-07-07 14:39 UTC, byDemid commented
качество изображения хворает, ну если это не принципиально, но придется еще поменять цвет шрифтов, или сделать обводку текста
text-shadow: 1px 0 1px #000, 0 1px 1px #000, -1px 0 1px #000, 0 -1px 1px #000
а то сливается белый текст на белом фоне в ЛК и историях

2022-07-07 20:02 UTC, IrinaMilekhina requested changes
Ждем картинки другие

2022-07-08 14:44 UTC, ZhenyaBardachina approved these changes, later dismissed

2022-07-08 14:45 UTC, ZhenyaBardachina commented
Добавили другие картинки

2022-07-09 09:22 UTC, IrinaMilekhina commented on ProductPlatform/ProductPlatform/script/change_order_status.logs
> +2022-07-05 21:33:23,949 WARNING change_order_status.py start thread check order...
файл добавлен в гитигнор и удален
надо ребейз или просто удалить и запушить

2022-07-09 09:47 UTC, IrinaMilekhina approved these changes

2022-07-09 13:06 UTC, morozov-git approved these changes

2022-07-09 13:16 UTC, merged