created included menu
IrinaMilekhina/WebTeam_Project pull request #15
Opened 2022-06-08 18:14 UTC by DanielPivnev

2022-06-08 19:51 UTC, IrinaMilekhina requested changes

2022-06-08 19:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/includes/inc_menu.html
> +<nav class="navbar navbar-expand-lg fixed-top bg-green">
надо теперь это меню в базовый щаблон воткнуть =)

2022-06-08 19:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/includes/inc_menu.html
> +                      d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-
а что это?

2022-06-08 19:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/users/includes/inc_menu.html
> +                        Администрация
??

2022-06-13 19:04 UTC, IrinaMilekhina approved these changes, later dismissed

2022-06-13 19:16 UTC, Sten451 reviewed
разве в России можно размещать на сайтах ссылки на facebook и т.п.

2022-06-13 20:05 UTC, Sten451 reviewed
Еще раз спрашиваю, насколько сейчас безопасно или правильно размещать значки фейсбука, инстаграмма они же признаны территористическими.

2022-06-13 21:02 UTC, IrinaMilekhina approved these changes

2022-06-13 21:24 UTC, kerleada7 approved these changes

2022-06-13 21:26 UTC, IrinaMilekhina approved these changes

2022-06-13 21:26 UTC, merged