corrected top category on main
IrinaMilekhina/WebTeam_Project pull request #150
Opened 2022-07-08 18:56 UTC by byDemid

В принципе тут все было хорошо, просто выводились категории, которые участвовали в заказе в течении 7 последних дней, добавил description в values для отображения на странице.
не могу вывести количество заказов в категории, точнее они тоже там есть но они за картинкой, в отладчике в браузере получается вывести а через скрипт нет, в чем проблема не понимаю.

2022-07-09 09:52 UTC, IrinaMilekhina requested changes
Этот пулл реквест не решает задачу
Надо обратиться к коллегам за помощью и добить задачу до конца

2022-07-09 12:55 UTC, morozov-git submitted a review, later dismissed

2022-07-09 19:44 UTC, DanielPivnev approved these changes, later dismissed

2022-07-10 16:44 UTC, Bekham approved these changes, later dismissed

2022-07-13 11:40 UTC, closed without merging