active responses and orders
IrinaMilekhina/WebTeam_Project pull request #162
Opened 2022-07-12 16:56 UTC by DanielPivnev

2022-07-14 09:50 UTC, IrinaMilekhina reviewed
а что будет написано в статусе на странице Активные заказы для таких вариантов?

2022-07-14 13:10 UTC, EuGeN-PYTHON requested changes
В темплейтах необходимо изменить Статус заказов на "Поставщик утвержден" или "Поставщик выполняет заказ"

2022-07-18 08:31 UTC, EuGeN-PYTHON approved these changes

2022-07-18 12:49 UTC, morozov-git approved these changes

2022-07-18 14:59 UTC, merged