611_top_categories_on_main
IrinaMilekhina/WebTeam_Project pull request #165
Opened 2022-07-13 11:36 UTC by byDemid

2022-07-14 07:57 UTC, DanielPivnev submitted a review, later dismissed

2022-07-14 08:25 UTC, EuGeN-PYTHON reviewed
Зачем мы упрощаем формулу до "Кол-во заказов"?

2022-07-14 14:52 UTC, EuGeN-PYTHON requested changes
Необходимо обновить main_fixture.json (добавить заказы и подтвержденные отклики на них)

2022-07-15 13:53 UTC, EuGeN-PYTHON approved these changes

2022-07-15 14:12 UTC, morozov-git approved these changes

2022-07-16 11:31 UTC, merged