Update README.md
IrinaMilekhina/WebTeam_Project pull request #178
Opened 2022-07-21 12:22 UTC by kerleada7

2022-07-22 09:17 UTC, IrinaMilekhina requested changes
Пришлю пример своего readme что бы стырить полезного =))

2022-07-22 09:17 UTC, IrinaMilekhina commented on README.md
> +python manage.py migrate # run first migration
а makemigrations?

2022-07-22 09:17 UTC, IrinaMilekhina commented on README.md
> +password: ADMIN
логины и пароле не пишутся в readme

2022-07-22 09:17 UTC, IrinaMilekhina commented on README.md
> +Это приложение предназначено для реализации продовольственных заказов. В которой кафе, рестораны выступают в роли заказчика и размещают на выполнение заказы на приобретение продовольственных товаров,
в котроМ

2022-07-23 09:48 UTC, IrinaMilekhina approved these changes

2022-07-23 10:34 UTC, EuGeN-PYTHON approved these changes

2022-07-23 16:40 UTC, merged