edit base template
IrinaMilekhina/WebTeam_Project pull request #20
Opened 2022-06-11 16:01 UTC by DanielPivnev

2022-06-11 17:54 UTC, Bekham submitted a review, later dismissed

2022-06-12 07:46 UTC, kerleada7 commented
Базовый шаблон должен находится не в юзерах. Перенеси его выше по иерархии. на одном уровне с приложениями

2022-06-12 10:21 UTC, IrinaMilekhina approved these changes

2022-06-12 10:23 UTC, IrinaMilekhina requested changes
Учесть коммент о структуре

2022-06-13 19:02 UTC, IrinaMilekhina approved these changes

2022-06-13 19:19 UTC, Sten451 approved these changes

2022-06-13 20:24 UTC, merged