Профиль - История заказов/откликов
IrinaMilekhina/WebTeam_Project pull request #45
Opened 2022-06-18 18:04 UTC by Bekham

2022-06-19 13:26 UTC, DanielPivnev submitted a review, later dismissed

2022-06-19 14:21 UTC, ivg97 submitted a review, later dismissed

2022-06-21 10:11 UTC, kerleada7 approved these changes, later dismissed

2022-06-21 10:13 UTC, EuGeN-PYTHON submitted a review, later dismissed

2022-06-21 14:33 UTC, EuGeN-PYTHON requested changes
Прошу исправить конфликты:

ProductPlatform/users/urls.py
ProductPlatform/users/views.py

2022-06-21 15:18 UTC, morozov-git approved these changes

2022-06-21 15:18 UTC, morozov-git commented on ProductPlatform/users/views.py
> +                'date_to': item.end_time.date(),
У меня с этой строкой не работает

2022-06-21 15:55 UTC, EuGeN-PYTHON requested changes

2022-06-21 15:55 UTC, EuGeN-PYTHON commented on ProductPlatform/users/urls.py
> +    path('account_history_orders/', PersonalHistoryOrdersView.as_view(), name='account_active_orders'),
изменить name. Дублирует Active_order

2022-06-21 15:55 UTC, EuGeN-PYTHON commented on ProductPlatform/users/views.py
> +            orders = Order.objects.filter(author=self.request.user.pk, status=False)
Разобраться со статусами моделей

2022-06-21 15:55 UTC, EuGeN-PYTHON commented on ProductPlatform/users/views.py
> +            responses = ResponseOrder.objects.filter(order__id__in=orders.values_list('id'), order__status=False)
Разобраться со статусами моделей

2022-06-21 17:00 UTC, EuGeN-PYTHON approved these changes, later dismissed

2022-06-22 08:32 UTC, IrinaMilekhina reviewed
А где ссылки на новые страницы?

2022-06-22 13:16 UTC, morozov-git approved these changes, later dismissed

2022-06-22 15:59 UTC, IrinaMilekhina requested changes
необходим ребейз

2022-06-22 17:21 UTC, IrinaMilekhina approved these changes

2022-06-22 17:32 UTC, EuGeN-PYTHON approved these changes

2022-06-22 17:55 UTC, merged