add main template
IrinaMilekhina/WebTeam_Project pull request #5
Opened 2022-06-04 17:51 UTC by DanielPivnev

2022-06-05 08:51 UTC, IrinaMilekhina requested changes

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +<!doctype html>
Некорректная структура для django. Все шаблоны должны лежать в app/templates/app/

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +    <nav class="navbar navbar-expand-lg fixed-top bg-green">
Меню необходимо вынести в подшаблон

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +                                <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5
Это что?

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
Ссылок на внешние источники быть не должно, нужно класть изображения в статику

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +<head>
Нужно сделать базовый шаблон с импортами

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
???

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +<div class="position-relative about overflow-hidden p-3 p-md-5  text-center bg-light">
откуда эти классы?

2022-06-05 08:51 UTC, IrinaMilekhina commented on ProductPlatform/users/templates/main.html
> +<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
положить в статику

2022-06-07 15:58 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +<!doctype html>
исправил

2022-06-07 16:03 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +    <nav class="navbar navbar-expand-lg fixed-top bg-green">
я лишь фронт делал для главной, поэтому лучше мож подождать с подшаблонам, потому-что  я ещё не дома как другие страницы выглядят?

2022-06-07 16:04 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +                                <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5
это иконки для меню

2022-06-07 16:04 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
исправил

2022-06-07 16:22 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +<head>
исправил

2022-06-07 16:22 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
исправил

2022-06-07 16:23 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +<div class="position-relative about overflow-hidden p-3 p-md-5  text-center bg-light">
bootstrap и свои

2022-06-07 16:23 UTC, DanielPivnev commented on ProductPlatform/users/templates/main.html
> +<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
исправил

2022-06-09 16:15 UTC, EuGeN-PYTHON approved these changes, later dismissed

2022-06-09 16:15 UTC, EuGeN-PYTHON commented on ProductPlatform/users/templates/users/main.html
> +    </footer>
Прошу вынести footer в Base.html

2022-06-13 19:33 UTC, IrinaMilekhina reviewed
Главным приложением у нас является orders, давай все что с главной страницей связано будет там

2022-06-14 07:37 UTC, IrinaMilekhina approved these changes

2022-06-14 07:38 UTC, kerleada7 approved these changes

2022-06-14 07:39 UTC, merged