393 table with filter on category
IrinaMilekhina/WebTeam_Project pull request #53
Opened 2022-06-19 18:04 UTC by Sten451

Доска заказов с фильтрацией по категории на js

2022-06-20 14:45 UTC, Sten451 commented
Есть проблема с отображением таблицы какой то конфликт с js видимо меню шаблона

2022-06-21 14:31 UTC, EuGeN-PYTHON requested changes
Прошу исправить конфликты:

ProductPlatform/orders/urls.py
ProductPlatform/orders/views.py

2022-06-21 16:51 UTC, Sten451 commented
исправил

2022-06-21 16:54 UTC, EuGeN-PYTHON approved these changes

2022-06-21 20:58 UTC, closed without merging