402_back_Suppliers_for_Categories
IrinaMilekhina/WebTeam_Project pull request #80
Opened 2022-06-27 11:45 UTC by EuGeN-PYTHON

2022-06-27 18:18 UTC, IrinaMilekhina commented on ProductPlatform/orders/views.py
> +    #         return render(request, self.template_name, {'ERROR': 'Страница не найдена', 'title': '404'})
а зачем закомментированные места?

2022-06-29 18:27 UTC, IrinaMilekhina submitted a review, later dismissed

2022-06-29 20:17 UTC, kerleada7 submitted a review, later dismissed

2022-07-02 12:50 UTC, IrinaMilekhina requested changes
требуется rebase

2022-07-02 17:22 UTC, closed without merging

2022-07-02 17:22 UTC, EuGeN-PYTHON commented
archive