finish
IrinaMilekhina/WebTeam_Project pull request #83
Opened 2022-06-27 12:10 UTC by kerleada7

2022-06-27 12:13 UTC, kerleada7 commented
После релиза нужно как продолжение(не захотел все в одной ветке делать):
1. Добавить валидацию на дату действия (можно в самой модели).
2. Изменить модель заказа - end_time - сделать DateField

2022-06-28 07:00 UTC, Bekham reviewed
При уменьшении разрешения то смартфона (12 Pro) - картинка заказа уходит наверх и появляется большая часть дефолтного изображения 300х150. Может поле Описание сместить вниз на отдельную строку? Это самое объемное поле, и, также, по мере сужения экрана - мета под описание практически не остается

2022-06-28 07:58 UTC, kerleada7 commented
Исправлено

2022-06-28 10:42 UTC, Bekham reviewed
Имеются небольшие, но существенные отклонения от фигмы:
1. Шапка "Описание"  и Наименование должна быть над полем для ввода - это важно при уменьшении размера экрана
2. Поле Наименования заказа должно быть на половину экрана

2022-06-28 11:06 UTC, kerleada7 commented
> Имеются небольшие, но существенные отклонения от фигмы:
> 
> 1. Шапка "Описание"  и Наименование должна быть над полем для ввода - это важно при уменьшении размера экрана
> 2. Поле Наименования заказа должно быть на половину экрана

Фигма это не истина. Фигма это просто макет, который может меняться.  и для телефонов делается отдельный шаблон.

2022-07-02 12:49 UTC, IrinaMilekhina requested changes
требуется rebase

2022-07-04 21:56 UTC, closed without merging