490_Moderator_page_Category
IrinaMilekhina/WebTeam_Project pull request #87
Opened 2022-06-27 15:42 UTC by EuGeN-PYTHON

2022-06-28 05:53 UTC, Bekham reviewed
Может стоит или вообще отказаться окна подтверждения - просто обновлять страницу категории ИЛИ добавить на страницу подтверждения кнопку Отмена с переходом на категорию?

2022-06-28 09:36 UTC, kerleada7 commented
Кнопку лучше вниз опустить.
И соглашусь, что подтверждение, нужно сделать немного по другому. Модальным окном будет приятнее.

2022-06-28 09:54 UTC, EuGeN-PYTHON commented
Я сделал заготовку для модального окна. Не умею их делать. Возьмем в следующий спринт. Пока через дом страницу.

2022-06-28 15:35 UTC, morozov-git approved these changes, later dismissed

2022-07-02 12:49 UTC, IrinaMilekhina requested changes
требуется rebase

2022-07-02 21:16 UTC, closed without merging